// <auto-generated />
// Source: Contracts/DynamicFormFlow/DYNAMIC_FORM_FLOW_CAPABILITY_CATALOG_V1_7.json
// Catalog SHA-256: semantic canonical JSON (recursively sorted object keys, preserved array order, UTF-8, no whitespace).
#nullable enable

using System;
using System.Collections.Generic;

namespace tdtd_be.Common.Capabilities;

public sealed record DynamicFormFlowCapabilityItemMetadata(
    string Id,
    string Name,
    string Status,
    string? TargetPhase,
    string TestPrefix,
    string UiSurface,
    string? Notes);

public sealed record DynamicFormFlowCapabilityDefaultsMetadata(
    bool PublishedFormSchemaMutable,
    bool AssignmentBindsFormVersionId,
    string EmptyFlowPolicy,
    string RuntimeRoleSource,
    string RawSourceReportAccess,
    string MappedTargetStatisticContribution,
    string FlowStatisticProfile);

public sealed record StatisticsConfigurationCapabilityMetadata(
    string Id,
    string Status,
    string? TargetPhase,
    string TestPrefix,
    string UiSurface,
    string Notes);

public static class DynamicFormFlowCapabilityCatalogMetadata
{
    public const string CatalogVersion = "1.7";
    public const string CatalogSha256 = "ccb28afafc068ac1b720c046a25276a35d9d828b14f9cc9c9bc690077ca204c1";
    public const string SchemaSha256 = "5842baf176bf1eec453b718d07e50da55a417aa9036f4f097ccfbb6fc58c1978";
    public const string ApprovedAt = "2026-08-10";
    public const string FlowScopeName = "BPMN_LITE_12_ARCHETYPES";
    public const bool FullBpmnClaimAllowed = false;
    public const bool UiGateContinuous = true;

    public static DynamicFormFlowCapabilityDefaultsMetadata Defaults { get; } = new(
        false,
        true,
        "DENY",
        "SERVER_DERIVED",
        "EXPLICIT_PERMISSION_ONLY",
        "EXCLUDE",
        "INTENTIONAL_BLOCK");

    public static IReadOnlyList<string> RequiredUiStates { get; } = Array.AsReadOnly(new[]
    {
        "LOADING",
        "EMPTY",
        "ERROR",
        "FORBIDDEN",
        "READONLY",
        "LOCKED",
        "STALE_CONFLICT",
        "SUCCESS",
        "RETRYING",
        "UNSUPPORTED",
    });

    public static IReadOnlyList<string> RequiredActors { get; } = Array.AsReadOnly(new[]
    {
        "OWNER",
        "ISSUER",
        "REPORTER",
        "REVIEWER",
        "COORDINATOR",
        "SYSTEM_ADMIN",
        "OUTSIDER",
    });

    public static IReadOnlyList<string> RequiredEvidence { get; } = Array.AsReadOnly(new[]
    {
        "COMPONENT_TEST",
        "BROWSER_TEST",
        "ACCESSIBILITY_SMOKE",
        "RESPONSIVE_REVIEW",
        "SCREENSHOT",
        "TRACE",
    });

    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> DynamicFormFieldTypes { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("shortText", "Nội dung cố định", "SUPPORTED", "P3", "DF-FIELD-SHORT_TEXT", "FORM_BUILDER_AND_REPORT_RUNTIME", "Một option code; không phải free text một dòng."),
        new DynamicFormFlowCapabilityItemMetadata("longText", "Nội dung nhiều dòng", "SUPPORTED", "P3", "DF-FIELD-LONG_TEXT", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("richText", "Soạn thảo văn bản", "SUPPORTED", "P3", "DF-FIELD-RICH_TEXT", "FORM_BUILDER_AND_REPORT_RUNTIME", "Phải sanitize; không là statistic target trong v1."),
        new DynamicFormFlowCapabilityItemMetadata("stringList", "Danh sách nội dung", "SUPPORTED", "P3", "DF-FIELD-STRING_LIST", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("number", "Số", "SUPPORTED", "P3", "DF-FIELD-NUMBER", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("date", "Ngày hoặc kỳ linh hoạt", "SUPPORTED", "P3", "DF-FIELD-DATE", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("fullDate", "Ngày đầy đủ", "SUPPORTED", "P3", "DF-FIELD-FULL_DATE", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("singleSelect", "Chọn một", "SUPPORTED", "P3", "DF-FIELD-SINGLE_SELECT", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("multiSelect", "Chọn nhiều", "SUPPORTED", "P3", "DF-FIELD-MULTI_SELECT", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("boolean", "Có hoặc không", "SUPPORTED", "P3", "DF-FIELD-BOOLEAN", "FORM_BUILDER_AND_REPORT_RUNTIME", null),
    });

    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> DynamicFormValueSources { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("FIXED_ENUM", "Danh sách cố định trong biểu mẫu", "SUPPORTED", "P3", "DF-SOURCE-01", "FORM_FIELD_SOURCE_EDITOR", null),
        new DynamicFormFlowCapabilityItemMetadata("ENUM_CATALOG", "Danh mục enum dùng chung", "SUPPORTED", "P3", "DF-SOURCE-02", "FORM_FIELD_SOURCE_EDITOR", null),
        new DynamicFormFlowCapabilityItemMetadata("SYSTEM_UNIT", "Đơn vị hệ thống", "SUPPORTED", "P3", "DF-SOURCE-03", "FORM_FIELD_SOURCE_EDITOR", null),
        new DynamicFormFlowCapabilityItemMetadata("SYSTEM_USER", "Người dùng hệ thống", "SUPPORTED", "P3", "DF-SOURCE-04", "FORM_FIELD_SOURCE_EDITOR", null),
        new DynamicFormFlowCapabilityItemMetadata("SYSTEM_POSITION", "Chức vụ hệ thống", "SUPPORTED", "P3", "DF-SOURCE-05", "FORM_FIELD_SOURCE_EDITOR", null),
        new DynamicFormFlowCapabilityItemMetadata("SYSTEM_UNIT_TYPE", "Loại đơn vị hệ thống", "SUPPORTED", "P3", "DF-SOURCE-06", "FORM_FIELD_SOURCE_EDITOR", null),
    });

    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> DynamicFormTableModes { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("FIXED_GRID", "Lưới cố định", "SUPPORTED", "P3", "DF-BLOCK-FIXED_GRID", "FORM_TABLE_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("APPEND_ROWS", "Thêm dòng", "SUPPORTED", "P3", "DF-BLOCK-APPEND_ROWS", "FORM_TABLE_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("APPEND_COLUMNS", "Thêm cột", "SUPPORTED", "P3", "DF-BLOCK-APPEND_COLUMNS", "FORM_TABLE_BUILDER_AND_REPORT_RUNTIME", "Form runtime target; flow mapping chỉ được công bố sau P7."),
        new DynamicFormFlowCapabilityItemMetadata("MATRIX", "Ma trận", "SUPPORTED", "P3", "DF-BLOCK-MATRIX", "FORM_TABLE_BUILDER_AND_REPORT_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("SUMMARY_TEMPLATE", "Mẫu kết quả tổng hợp", "SUPPORTED", "P3", "DF-BLOCK-SUMMARY_TEMPLATE", "FORM_TABLE_BUILDER_AND_SUMMARY_RESULT", "Read-only output; không dùng làm nguồn nhập trực tiếp."),
    });

    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> DynamicFlowArchetypes { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T01", "Một bước, một form, một đơn vị", "SUPPORTED", "P5", "FLOW-T01", "FLOW_BUILDER_AND_INSTANCE_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T02", "Một bước fan-out nhiều đơn vị", "SUPPORTED", "P5", "FLOW-T02", "FLOW_BUILDER_AND_INSTANCE_RUNTIME", "Phải atomic hoặc durable-saga và idempotent."),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T03", "Tuần tự A đến B đến C, nhiều form", "SUPPORTED", "P6", "FLOW-T03", "FLOW_TOPOLOGY_AND_STEP_RUNTIME", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T04", "Fork song song", "SUPPORTED", "P6", "FLOW-T04", "FLOW_TOPOLOGY_AND_INSTANCE_TREE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T05", "Fan-in ALL", "SUPPORTED", "P6", "FLOW-T05", "FLOW_GATEWAY_EDITOR_AND_INSTANCE_TREE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T06", "Fan-in ANY hoặc N_OF_M", "SUPPORTED", "P6", "FLOW-T06", "FLOW_GATEWAY_EDITOR_AND_INSTANCE_TREE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T07", "Gateway điều kiện có kiểu", "SUPPORTED", "P6", "FLOW-T07", "FLOW_CONDITION_EDITOR_AND_INSTANCE_TIMELINE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T08", "Review, trả lại và gửi lại", "SUPPORTED", "P6", "FLOW-T08", "REPORT_REVIEW_AND_STEP_TIMELINE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T09", "Subflow", "SUPPORTED", "P6", "FLOW-T09", "FLOW_SUBFLOW_EDITOR_AND_INSTANCE_TREE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T10", "Instance định kỳ", "SUPPORTED", "P6", "FLOW-T10", "FLOW_SCHEDULE_EDITOR_AND_INSTANCE_LIST", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T11", "Bước bổ sung có kiểm soát", "SUPPORTED", "P6", "FLOW-T11", "FLOW_STEP_ACTION_AND_TIMELINE", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW-T12", "Rollback, terminate, restart và finalize", "SUPPORTED", "P6", "FLOW-T12", "FLOW_INSTANCE_ACTIONS_AND_TIMELINE", null),
    });

    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> StatisticsCapabilities { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("DIRECT_FIELD_TABLE_LABEL", "Projection và thống kê trực tiếp field, table, label", "SUPPORTED", "P9", "STAT-DIRECT", "STAT_RESULT_AND_DRILLDOWN", null),
        new DynamicFormFlowCapabilityItemMetadata("BASIC_SUMMARY", "Tổng hợp cơ bản", "SUPPORTED", "P9", "STAT-BASIC", "STAT_CONFIG_JOB_AND_RESULT", null),
        new DynamicFormFlowCapabilityItemMetadata("ADVANCED_SUMMARY", "Tổng hợp nâng cao", "SUPPORTED", "P9", "STAT-ADVANCED", "STAT_CONFIG_JOB_AND_RESULT", null),
        new DynamicFormFlowCapabilityItemMetadata("DIFF", "So sánh sai khác", "SUPPORTED", "P9", "STAT-DIFF", "STAT_DIFF_CONFIG_AND_RESULT", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW_SCOPES", "FLOW_BRANCH, FLOW_STEP, FLOW_EFFECTIVE_PATH và FLOW_FINAL", "SUPPORTED", "P9", "STAT-FLOW", "STAT_SCOPE_CONFIG_JOB_AND_RESULT", null),
        new DynamicFormFlowCapabilityItemMetadata("FLOW_STATISTIC_PROFILE", "Flow statisticProfile executor", "INTENTIONAL_BLOCK", null, "STAT-PROFILE-BLOCK", "FLOW_STATISTIC_PROFILE_DISABLED", "Giữ chặn cho tới khi có executor versioned, rebuild, permission và UAT riêng."),
    });
    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> DynamicFlowMappingCapabilities { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("FIELD_TYPED", "Typed field mapping", "SUPPORTED", "P7", "MAP-FIELD", "FLOW_MAPPING_DEFINITION_AND_REPORT_RUNTIME", "Typed copy and multi-input calculation use the same versioned safe evaluator for validation, preview and apply."),
        new DynamicFormFlowCapabilityItemMetadata("FIXED_GRID", "Fixed-grid target mapping", "SUPPORTED", "P7", "MAP-TABLE-FIXED-GRID", "FLOW_MAPPING_DEFINITION_AND_REPORT_RUNTIME", "Target identity is exact blockId, columnKey, rowKey and value-slot/index-map identity; positional fallback is forbidden."),
        new DynamicFormFlowCapabilityItemMetadata("APPEND_ROWS", "Append-rows target mapping", "SUPPORTED", "P7", "MAP-TABLE-APPEND-ROWS", "FLOW_MAPPING_DEFINITION_AND_REPORT_RUNTIME", "The canonical source row key, scoped by mapping ID and version, is the idempotent target row business key."),
        new DynamicFormFlowCapabilityItemMetadata("MATRIX_SPARSE", "Matrix and sparse target mapping", "SUPPORTED", "P7", "MAP-TABLE-MATRIX-SPARSE", "FLOW_MAPPING_DEFINITION_AND_REPORT_RUNTIME", "Exact sparse coordinates keep values1D, value slots, index maps and matrix cells synchronized without positional fallback."),
        new DynamicFormFlowCapabilityItemMetadata("SOURCE_REPORT_GRAIN", "Source-report evaluation grain", "SUPPORTED", "P7", "MAP-SOURCE-REPORT-GRAIN", "FLOW_MAPPING_DEFINITION_AND_REPORT_RUNTIME", "Each exact authorized source report is evaluated independently and bound to its runtime and source-signature identity."),
        new DynamicFormFlowCapabilityItemMetadata("GROUP_GRAIN", "Group evaluation grain", "INTENTIONAL_BLOCK", null, "MAP-BLOCK-GROUP-GRAIN", "FLOW_MAPPING_DEFINITION_DISABLED", "Blocked with DYNAMIC_FLOW_MAPPING_GROUP_INTENTIONAL_BLOCK."),
        new DynamicFormFlowCapabilityItemMetadata("CUSTOM_JOIN_KEY", "Custom join key", "INTENTIONAL_BLOCK", null, "MAP-BLOCK-CUSTOM-JOIN-KEY", "FLOW_MAPPING_DEFINITION_DISABLED", "Blocked with DYNAMIC_FLOW_MAPPING_CUSTOM_JOIN_KEY_INTENTIONAL_BLOCK; null or blank selects the canonical row-key join."),
        new DynamicFormFlowCapabilityItemMetadata("APPEND_COLUMNS_TARGET", "Append-columns target mapping", "INTENTIONAL_BLOCK", null, "MAP-BLOCK-APPEND-COLUMNS-TARGET", "FLOW_MAPPING_DEFINITION_DISABLED", "Blocked with DYNAMIC_FLOW_MAPPING_APPEND_COLUMNS_TARGET_INTENTIONAL_BLOCK; exact APPEND_COLUMNS source reads remain read-only."),
        new DynamicFormFlowCapabilityItemMetadata("SCALAR_TO_ROW", "Scalar-to-row mapping", "INTENTIONAL_BLOCK", null, "MAP-BLOCK-SCALAR-TO-ROW", "FLOW_MAPPING_DEFINITION_DISABLED", "Blocked with DYNAMIC_FLOW_MAPPING_SCALAR_TO_ROW_INTENTIONAL_BLOCK."),
        new DynamicFormFlowCapabilityItemMetadata("ROW_TO_REPORT", "Row-to-report mapping", "INTENTIONAL_BLOCK", null, "MAP-BLOCK-ROW-TO-REPORT", "FLOW_MAPPING_DEFINITION_DISABLED", "Blocked with DYNAMIC_FLOW_MAPPING_ROW_TO_REPORT_INTENTIONAL_BLOCK."),
    });
    public static IReadOnlyList<StatisticsConfigurationCapabilityMetadata> StatisticsConfigurationCapabilities { get; } = Array.AsReadOnly(new[]
    {
        new StatisticsConfigurationCapabilityMetadata("LABEL_TAXONOMY_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-LABEL", "STAT_LABEL_CONFIG", "Four layers stay distinct; classification never contributes."),
        new StatisticsConfigurationCapabilityMetadata("FIELD_METADATA_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-FIELD", "FORM_STATISTIC_FIELD_CONFIG", "Config/version/readback only; Form structure immutable; no result."),
        new StatisticsConfigurationCapabilityMetadata("TABLE_METADATA_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-TABLE", "FORM_STATISTIC_TABLE_CONFIG", "Stable metricKey; block-local disable; no positional fallback."),
        new StatisticsConfigurationCapabilityMetadata("BASIC_SUMMARY_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-BASIC", "STAT_BASIC_CONFIG", "Typed operation/scope/target/period/grouping; no run."),
        new StatisticsConfigurationCapabilityMetadata("FLOW_SCOPE_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-FLOW-SCOPE", "STAT_FLOW_SCOPE_CONFIG", "Four FLOW selectors readable/versioned; runtime P9-blocked."),
        new StatisticsConfigurationCapabilityMetadata("ADVANCED_SUMMARY_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-ADVANCED", "STAT_ADVANCED_CONFIG", "Draft/lock/version/gates/hierarchy/empty/budget; WorkSummaryToken stays a quota ledger."),
        new StatisticsConfigurationCapabilityMetadata("DIFF_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-DIFF", "STAT_DIFF_CONFIG", "Compatible concept/period/direction/scope/missing; no delta."),
        new StatisticsConfigurationCapabilityMetadata("FLOW_CONTRIBUTION_CONFIG", "SUPPORTED", "P8", "STAT-CONFIG-CONTRIBUTION", "FLOW_STATISTIC_CONTRIBUTION_CONFIG", "V_EXCLUDE/V_INCLUDE; EXCLUDE default; preserve P7; no result."),
        new StatisticsConfigurationCapabilityMetadata("FLOW_STATISTIC_PROFILE_BARRIER", "SUPPORTED", "P8", "STAT-CONFIG-PROFILE-BARRIER", "FLOW_STATISTIC_PROFILE_DISABLED", "Non-empty fail-closed validation barrier only; no executor."),
        new StatisticsConfigurationCapabilityMetadata("CONFIG_OPERATIONS_READINESS", "SUPPORTED", "P8", "STAT-CONFIG-OPS", "STAT_CONFIG_OPERATIONS_READINESS", "Indexes/no-dataset worker/diagnostics/quota/cleanup; no official rows."),
        new StatisticsConfigurationCapabilityMetadata("CONFIG_BUNDLE_READBACK", "SUPPORTED", "P8", "STAT-CONFIG-BUNDLE", "STAT_CONFIG_BUNDLE_READBACK", "Exact pins/empty eligibility/P9-P10 fail closed."),
    });
    public static IReadOnlyList<DynamicFormFlowCapabilityItemMetadata> StatisticsReconciliationCapabilities { get; } = Array.AsReadOnly(new[]
    {
        new DynamicFormFlowCapabilityItemMetadata("SOURCE_TO_RESULT_RECONCILIATION", "Source-to-result statistics reconciliation", "SUPPORTED", "P10", "P10-RECONCILE", "STAT_RECONCILIATION", null),
        new DynamicFormFlowCapabilityItemMetadata("EXPECTED_ACTUAL_DELTA", "Expected-versus-actual typed delta", "SUPPORTED", "P10", "P10-DELTA", "STAT_RECONCILIATION", null),
        new DynamicFormFlowCapabilityItemMetadata("INDEPENDENT_REVIEW_SIGNOFF", "Independent reconciliation review sign-off", "SUPPORTED", "P10", "P10-REVIEW", "STAT_RECONCILIATION_REVIEW", null),
        new DynamicFormFlowCapabilityItemMetadata("RECONCILIATION_EVIDENCE_EXPORT", "Deterministic reconciliation evidence export", "SUPPORTED", "P10", "P10-EVIDENCE", "STAT_RECONCILIATION_EVIDENCE", null),
    });
}
